config/routes.rb
Rails.application.routes.draw do
  get 'post_categories/new'
  get 'post_categories/create'
  get 'post_categories/destroy'
  root to: 'static_pages#home'
  get 'home', to: "static_pages#home"
  get 'about', to: "static_pages#about"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :users
  resources :posts
  resources :comments, only: [:create, :destroy, :update]
  resources :categories
  resources :post_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
  
end

app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  def new
    @post_category = PostCategory.new
  end

  def index
    @post_categories = PostCategory.all
  end

  def create
      @post_category = PostCategory.new(post_category_params)
    if @post_category.save
      flash[:success] = "作成が完了しました"
      redirect_to post_categories_url
    else
      redirect_to post_categories_url
    end
  end

  def destroy
    @post_category = PostCategory.find(params[:id])
    @post_category.destroy
    flash[:success] = "削除しました"
     redirect_to post_categories_url
    end
  end

private

    def post_category_params
      params.require(:post_category).permit(:post_id, :category_id)
    end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/views/post_categories/_form.html.erb
<%= form_for @post_category do |f| %>
<ul>
  <%= f.label :post_id, "ポスト" %>
  <%= f.collection_select :post_id, current_user.posts, :id, :title %>

  <%= f.label :category_id, "カテゴリー" %>
  <%= f.collection_select :category_id, Category.all, :id, :name %>
  <%= f.submit class:"form__items form__items--submit"  %>
</ul>
<% end %>

app/views/post_categories/_post_category.html.erb

  <ul>
    <%= post_category.post.title %>
    <%= post_category.category.name %>
    <%= link_to 'Destroy', post_category, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
  </ul>

app/views/post_categories/index.html.erb
<h1>関連づけ一覧</h1>

<%= render @post_categories %>

<%= link_to 'カテゴリの作成', categories_path, style:"margin-left:10px;" %>
<%= link_to "カテゴリー関連付け", new_post_category_path, class: 'center', style: 'margin: 20px 0px;' %>
<%= link_to "カテゴリー一覧へ", '/categories', class: 'center', style: 'margin: 20px 0px;' %>

app/views/post_categories/new.html.erb
<h1>カテゴリー関連付け</h1>

<%= render 'form' %>

<%= link_to "カテゴリー一覧へ", '/categories', class: 'center', style: 'margin: 20px 0px;' %>
<%= link_to '関連づけ一覧へ', post_categories_path, style:"margin-left:10px;" %>