config/routes.rb
Rails.application.routes.draw do
  get 'post_categories/new'
  get 'post_categories/create'
  get 'post_categories/destroy'
  root to: 'static_pages#home'
  get 'home', to: "static_pages#home"
  get 'about', to: "static_pages#about"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :users
  resources :posts
  resources :comments, only: [:create, :destroy, :update]
  resources :categories
  resources :post_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  validates :post, uniqueness: { scope: :category_id }

  validates :content, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only:[:edit, :update, :destroy]

  def index
    @posts = current_user.posts
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿が完了しました"
      redirect_to @post
    else
      flash.now[:danger] = "投稿に失敗しました"
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "投稿の編集が完了しました"
      redirect_to @post
    else
      flash.now[:warning] = "投稿の編集に失敗しました"
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "投稿を削除しました"
      redirect_to posts_url
    else
      flash[:warning] = "投稿を削除できませんでした"
      redirect_to posts_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def correct_user
    # 実装してください
    @post = current_user.posts.find_by(id: params[:id])
      flash[:notice] = "権限がありません"
      redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= f.label :title, 'タイトル', class:"form__items form__items--label" %>
<%= f.text_field :title, class:"form__items form__items--input" %>

<%= f.label :content, '本文', class:"form__items form__items--label" %>
<%= f.text_area :content, style: 'width:100%;' %>

<%= f.submit class:"form__items form__items--submit"  %>

<script>
  $(function() {
    $('#post_content').froalaEditor();
  });
</script>

app/views/posts/_post.html.erb
<div class="post--card">
  <%= link_to post_path(post), class:"post--card__title post--card__bg-color-1" do %>
    <span><%= post.title %></span>
  <% end %>
  <div class="post--card__content--container">
    <div class="post--card__content--info"><span class="post--card__content--user">投稿者 <%= post.user_name %></span><span class="post--card__content--published"><%= post.created_at.strftime("%Y/%m/%d %H:%M:%S") %></span></div>
    <span class="post--card__content--content"><%= simple_format(post.card_content) %></span>
    <span class="post--card__content--continude"><%= link_to "続きを読む", post_path(post) %></span>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:btn_text, '更新する') %>

<div class="posts--new">
  <%= form_with model: @post, class:"form" do |f| %>
    <%= render 'form', f:f %>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="center">投稿一覧</h1>
<div class="posts-index">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<% provide(:btn_text, '投稿する') %>
<div class="posts--new">
  <%= form_for @post, class:"form" do |f| %>
    <%= render 'form', f:f %>
  <% end %>
</div>

app/views/posts/show.html.erb
<article class="posts--show">
  <h2 class="title"><span><%= @post.title %></span></h2>
  <section class="content"><%= simple_format(@post.content) %></section>
  <div class="comments-container">
    <div style="border-top: solid 1px #777;">
  <%= link_to "編集", edit_post_path, class: 'center', style: 'margin: 20px 0px;' %>
  <%= link_to "削除", @post, method: :delete, data: { confirm: "本当によろしいですか？" }, class: 'center', style: 'margin: 20px 0px;' %>
  
  <p> カテゴリ </p>
  <% @post.categories.each do |category| %>
    <div class="category"><%= category.name %></div>
  <% end %>


      <h2 class="center">コメント一覧</h2>
      <%= render @comments %>
    </div>
    <%= form_for @post.comments.build, class: 'comment-form' do |c| %>
      <%= c.hidden_field :post_id, value: @post.id %>
      <%= c.hidden_field :user_id, value: current_user ? current_user.id : "" %>
      <%= c.text_area :content %>
      <div class="submit-container">
        <%= c.submit '投稿', class: 'comment-submit' %>
      </div>
    <% end %>
  </div>
  <%= link_to "一覧へ戻る", posts_path, class: 'center', style: 'margin: 20px 0px;' %>
</article>
<script>
  $(function() {
    $('#comment_content').froalaEditor();
  });
</script>