config/routes.rb
Rails.application.routes.draw do
  get 'post_categories/new'
  get 'post_categories/create'
  get 'post_categories/destroy'
  root to: 'static_pages#home'
  get 'home', to: "static_pages#home"
  get 'about', to: "static_pages#about"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :users
  resources :posts
  resources :comments, only: [:create, :destroy, :update]
  resources :categories
  resources :post_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "作成が完了しました"
      redirect_to categories_url
    else
      render categories_url
    end
  end


  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'カテゴリーを更新しました。'
    else
      render 'edit'
    end
  end


  def destroy
    @category = Category.find(params[:id])
    if  @category.destroy
      flash[:success] = "カテゴリを削除しました"
      redirect_to categories_url
    else
      flash[:warning] = "カテゴリを削除できませんでした"
      redirect_to categories_url
    end
  end

    private
      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name)
      end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<%= form_for(@post.categories.build) do |f| %>
  <%= f.label :"カテゴリー登録" %>
  <%= f.text_field :name, placeholder: "カテゴリー名" %>
  <%= f.submit "登録" %>
<% end %>

app/views/categories/_category.html.erb
 <ul>
   <%= category.name %>
   <%= link_to 'Destroy', category, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
 </ul>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h1>カテゴリー一覧</h1>

<%= render @categories %>

<%= link_to "カテゴリー作成", new_category_path, class: 'center', style: 'margin: 20px 0px;' %>
<%= link_to "カテゴリー関連付け", new_post_category_path, class: 'center', style: 'margin: 20px 0px;' %>
<%= link_to '関連づけ一覧へ', post_categories_path, style:"margin-left:10px;" %>

app/views/categories/new.html.erb
<h1>カテゴリ作成</h1>

<%= render 'form' %>

<%= link_to "カテゴリー一覧へ", '/categories', class: 'center', style: 'margin: 20px 0px;' %>
<%= link_to "カテゴリー関連付け", new_post_category_path, class: 'center', style: 'margin: 20px 0px;' %>
<%= link_to '関連づけ一覧へ', post_categories_path, style:"margin-left:10px;" %>