config/routes.rb
Rails.application.routes.draw do
  get 'post_categories/new'
  get 'post_categories/create'
  get 'post_categories/destroy'
  root to: 'static_pages#home'
  get 'home', to: "static_pages#home"
  get 'about', to: "static_pages#about"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :users
  resources :posts
  resources :comments, only: [:create, :destroy, :update]
  resources :categories
  resources :post_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  validates :post, uniqueness: { scope: :category_id }

  validates :content, presence: true

end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },length: { maximum: 100 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    if session[:user_id].nil?
      return false
    else
      return true
    end
  end

  def current_user
    if logged_in?
      @user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user, :logged_in?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "作成が完了しました"
      redirect_to categories_url
    else
      render categories_url
    end
  end


  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'カテゴリーを更新しました。'
    else
      render 'edit'
    end
  end


  def destroy
    @category = Category.find(params[:id])
    if  @category.destroy
      flash[:success] = "カテゴリを削除しました"
      redirect_to categories_url
    else
      flash[:warning] = "カテゴリを削除できませんでした"
      redirect_to categories_url
    end
  end

    private
      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name)
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def destroy
    @comment = Comment.preload(:post,{post: :user}).find(params[:id])
    @post = @comment.post
    @user = @post.user
    if @comment.destroy
      flash[:success] = "コメントの削除が完了しました"
      redirect_to @post
    else
      flash[:warning] = "コメントの削除に失敗しました"
      redirect_to @post
    end
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:success] = "コメントを作成しました"
      redirect_to @comment.post
    else
      flash[:warning] = "コメントの作成に失敗しました"
      redirect_to @comment.post
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.preload(:post,{post: :user}).find(params[:id])
    @post = @comment.post
    @user = @post.user
    if @comment.update_attributes(comment_params)
      flash[:success] = "コメントを更新しました"
      redirect_to @post
    else
      flash.now[:warning] = "コメントの編集に失敗しました"
      render 'edit'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :user_id, :content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only:[:edit, :update, :destroy]

  def index
    @posts = current_user.posts
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿が完了しました"
      redirect_to @post
    else
      flash.now[:danger] = "投稿に失敗しました"
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "投稿の編集が完了しました"
      redirect_to @post
    else
      flash.now[:warning] = "投稿の編集に失敗しました"
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "投稿を削除しました"
      redirect_to posts_url
    else
      flash[:warning] = "投稿を削除できませんでした"
      redirect_to posts_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def correct_user
    # 実装してください
    @post = current_user.posts.find_by(id: params[:id])
      flash[:notice] = "権限がありません"
      redirect_to root_url if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email].downcase)
    if @user && @user.authenticate(params[:password])
      login(@user)
      flash[:success] = "ログインに成功しました"
      redirect_to root_path
    else
      flash[:warning] = "メールアドレス、またはパスワードが間違っています"
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end

  private

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_user?, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user?, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to root_path
    else
      flash.now[:danger] = "ユーザーの作成に失敗しました"
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "情報の更新が完了しました"
      redirect_to @user
    else
      flash.now[:warning] = "情報の更新に失敗しました"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーの削除が完了しました"
    redirect_to 'index'
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @comments = @user.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def login_user?
    unless logged_in?
      flash[:warning] = "ログインしてください"
      redirect_to root_path
    end
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user?
    flash[:warning] = "管理者権限がありません"
    redirect_to root_url and return
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
	<%= content_tag(:div, class: "alert alert-#{message_type} sp-alert sp-alert-#{message_type}") do %>
    <div class="alert__icon sp-alert__icon">
      <% if message_type == "danger" %>
        <i class="fa fa-ban"></i>
      <% elsif message_type == "info" %>
        <i class="fa fa-info"></i>
      <% elsif message_type == "success" %>
        <i class="fa fa-check-circle"></i>
      <% elsif message_type == "warning" %>
        <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="alert__message sp-alert__message">
      <%= content_tag(:span, message) %>
    </div>
	<% end %>
<% end %>

app/views/layouts/_form_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="header">
  <div class="header__logo">
    <a href="/">
      <img src="/sf_logo2.png" alt="sf_logo" width="160">
    </a>
  </div>
  <div>
    <%= link_to about_path, class:"header__items__item change-border01 button" do %>
      <span class="change-border01__inner"><i class="fa fa-info-circle" aria-hidden="true"></i>About</span>
    <% end %>
  </div>
  <div>
    <%= link_to users_path, class:"header__items__item change-border02 button" do %>
      <span class="change-border02__inner"><i class="fa fa-users" aria-hidden="true"></i>Users</span>
    <% end %>
  </div>
  <% if logged_in? %>
    <div>
      <%= link_to user_path(current_user), class:"header__items__item" do %>
        <i class="fa fa-user"></i><%= current_user.name %>
      <% end %>
    </div>
    <div>
      <%= link_to new_post_path, class:"header__items__item accent" do %>
        <strong><i class="fa fa-pencil-square-o" aria-hidden="true"></i>new post</strong>
      <% end %>  
    </div>
    <div>
      <%= link_to logout_path, class:"header__items__item change-border01 button" do %>
        <span class="change-border01__inner"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</span>
      <% end %>
    </div>
  <% else %>
    <div>
      <%= link_to login_path, class:"header__items__item change-border01 button" do %>
        <span class="change-border01__inner"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</span>
      <% end %>
    </div>
    <div>
      <%= link_to new_user_path, class:"header__items__item accent" do %>
        <strong><i class="fa fa-user-plus" aria-hidden="true"></i>Sign up</strong>
      <% end %>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartfarmerexams</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_message' %>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/form_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>